-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM (
    SELECT BOOK.BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE, SALES_DATE, SUM(BOOK_SALES.SALES) AS SALES
    FROM BOOK_SALES
    JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
    GROUP BY BOOK_ID
    ) AS FIRST_JOIN
JOIN AUTHOR ON FIRST_JOIN.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY AUTHOR_NAME, FIRST_JOIN.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, CATEGORY DESC