-- 코드를 입력하세요
SELECT DATE_FORMAT(SHOP.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, SHOP.PRODUCT_ID, SHOP.USER_ID, SHOP.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
) AS SHOP
WHERE SHOP.SALES_DATE LIKE '2022-03%'
ORDER BY SHOP.SALES_DATE, SHOP.PRODUCT_ID, USER_ID