SELECT DISTINCT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I, ITEM_TREE AS T
WHERE I.ITEM_ID IN ( 
    SELECT T2.ITEM_ID 
    FROM ITEM_INFO AS I2, ITEM_TREE AS T2 
    WHERE I2.ITEM_ID = T2.PARENT_ITEM_ID AND I2.RARITY = 'RARE'
    ) 
ORDER BY I.ITEM_ID DESC