-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, substr(B.CREATED_DATE, 1, 10) as CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE substr(A.CREATED_DATE, 1, 4) = 2022 AND substr(A.CREATED_DATE, 6, 7) = 10
ORDER BY B.CREATED_DATE, A.TITLE