-- 코드를 입력하세요
SELECT CATEGORY, SUM(NOW_SALES) AS TOTAL_SALES
FROM BOOK
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS NOW_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '1'
    GROUP BY BOOK_ID ) AS SALE_INFO 
    ON BOOK.BOOK_ID = SALE_INFO.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY
